# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.5.0"

default_platform :ios

platform :ios do

  scheme = 'SwipeIt'
  commit = last_git_commit
  run_location = is_ci? ? 'Travis' : 'Local'

  before_all do
    # ensure_git_status_clean
    ENV["SLACK_URL"] = ENV['SWIPEIT_SLACK_URL']

    slack(
      channel: "swipeit",
      payload: {
        'Message' => commit[:message],
        'Author' => commit[:author],
        'Commit' => "https://github.com/ivanbruel/SwipeIt/commit/#{commit[:commit_hash]}"
      },
      default_payloads: [],
      message: "#{run_location} running Fastlane #{lane_context[SharedValues::LANE_NAME]}")

    cocoapods(repo_update: true)

    create_keychain(
      name: scheme,
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      lock_when_sleeps: true,
      password: SecureRandom.base64
    )

    # increment_build_number

  end

  desc "Runs all the unit tests"
  desc "Submits a new Beta Build to Fabric"
  desc "Submits a new Beta Build to Apple TestFlight"
  lane :travis do
    test
    fabric
    itc
  end

  desc "Runs all the unit tests"
  lane :test do
    scan(scheme: scheme)
  end

  desc "Submit a new Beta Build to Fabric"
  desc "This will also make sure the profile is up to date"
  lane :fabric do
    build_number = Time.new.strftime("%y%m%d.%H%M")
    increment_build_number build_number: build_number
    fabric_beta(scheme: scheme)
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :itc do
    itunes(scheme: scheme)
  end

  private_lane :fabric_beta do |options|
    scheme = options[:scheme]

    # Import distribution certificate
    import_certificate(
      certificate_path: "fastlane/certificates/development.p12",
      certificate_password: ENV["SWIPEIT_DEVELOPMENT_KEY"],
      keychain_name: scheme
    )

    sigh(
      development: true,
      output_path: "/tmp/"
    )

    build(
      scheme: scheme,
      signId: ENV['SWIPEIT_SIGNING_IDENTITY_DEV']
    )

    environment = scheme.upcase

    crashlytics(
      api_token: ENV['SWIPEIT_FABRIC_CLIENT_ID'],
      build_secret: ENV['SWIPEIT_FABRIC_SECRET'],
      ipa_path: "/tmp/#{scheme}.ipa",
      notes: commit[:message],
      groups: ["#{scheme}"]
    )

  end

  private_lane :itunes do |options|
    scheme = options[:scheme]


    # Import distribution certificate
    import_certificate(
      certificate_path: "fastlane/certificates/distribution.p12",
      certificate_password: ENV["SWIPEIT_DISTRIBUTION_KEY"],
      keychain_name: scheme
    )

    sigh(
      skip_install: true,
      development: false,
      output_path: "/tmp"
    )

    build(
      scheme: scheme,
      signId: ENV['SWIPEIT_SIGNING_IDENTITY_PROD']
    )

    pilot(
      ipa: "/tmp/#{scheme}.ipa",
      skip_submission: true,
      team_id: ENV['SWIPEIT_ITUNES_TEAM_ID'],
      skip_waiting_for_build_processing: true
    )

  end

  private_lane :build do |options|
    scheme = options[:scheme]
    signingId = options[:signId]

    gym(
      scheme: "#{scheme}",
      configuration: scheme,
      use_legacy_build_api: false,
      include_bitcode: true,
      workspace: "#{scheme}.xcworkspace",
      output_directory: "/tmp", # Change to temp folder
      output_name: "#{scheme}.ipa",
      codesigning_identity: "#{signingId}",
      clean: false,
      xcargs: "ARCHIVE=YES" # Used to tell the Fabric run script to upload dSYM file
    )
  end


  # This lane is called, only if the executed lane was successful
  after_all do |lane|
    notification(message: "Fastlane finished '#{lane}' successfully") # Mac OS X Notification
    slack(
      channel: "swipeit",
      payload: {
        'Message' => commit[:message],
        'Author' => commit[:author],
        'Commit' => "https://github.com/ivanbruel/SwipeIt/commit/#{commit[:commit_hash]}"
      },
      default_payloads: [],
      message: "#{run_location} successfully distributed #{scheme} into #{lane} :rocket:")
  end

  error do |lane, exception|
    notification(message: "#{run_location} Fastlane '#{lane}' errored") # Mac OS X Notification
    slack(message: exception.to_s, success: false)
  end
end



# More information about multiple platforms in fastlane: https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
